package com.example.enums;

public enum Step {
    MAIN,AddOrder,ORDER,SETTINGS,LANG,PHONE,
    GET_NAME_OF_MENU, GET_NAME_OF_ADMIN, GET_PHONE_OF_ADMIN, DELETE_ADMIN_BY_PHONE, CASH, SAVAT,
    MEAL, CHOOSEMEAL, NAME, SAVE_MENU,TYPE_METHOD, DELIVERY,OLIB_KETISH,CONFIRM,ADD_MENU_NAME, ADMIN_MAIN,
    ADD_MEALS_NAME, ADD_MEALS_PRICE, MEALS_DELETE, MEALS_DELETE_ID, MEALS_UPDATE_PRICE, MEALS_UPDATE_BY_ID,
    MEALS_UPDATE,
    GETPRICE, PRICE_MONEY, DELETE_MENU, MENU_DELETE_BY_ID, ADMIN_FULL_NAME, ADMIN_PHONE,
    ADMIN_PASSWORD, DELETE_ADMIN, ADMIN_LIST, MEALS_LIST, SUPPLIER_NAME, SUPPLIER_PASSWORD, SUPPLIER_PHONE,
    DELETE_SUPPLIER, SUPPLIER_LIST, MEALS_MENU_lIST, ADD_MEALS_PHOTO, COMMENT, HOLAT, UPDATE_PRICE
    , REGISTER, START,
}
