package com.example.enums;

public enum Step {
    MAIN,AddOrder,ORDER,SETTINGS,LANG,PHONE,
    GET_NAME_OF_MENU, GET_NAME_OF_ADMIN, GET_PHONE_OF_ADMIN, DELETE_ADMIN_BY_PHONE, CASH, SAVAT, MEAL, CHOOSEMEAL, NAME, SAVE_MENU,TYPE_METHOD
}
